name: Lara CI FSE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
        
jobs:
  ci: 
    runs-on: ubuntu-latest
            
    steps:
      - name: Checkout my code 
        uses: actions/checkout@v4
       
      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
        
      - name: Composer Install
        run: composer install --no-interaction --no-progress --optimize-autoloader
       
      - name: Prepare Laravel
        run: | 
          cp .env.example .env
          php artisan key:generate
          
      - name: Run Laravel Tests
        run: php artisan test
    
  # cd:
  #   needs: ci
  #   runs-on: ubuntu-latest
      
  #   steps:
  #     - name: Checkout my Code
  #       uses: actions/checkout@v4
      
  #     - name: Connect to EC2 Server
  #       uses: appleboy/ssh-action@v1.2.1
  #       with:
  #         host: ${{secrets.EC2_HOST}}
  #         username: ${{secrets.EC2_USER}}
  #         key: ${{secrets.EC2_SSH_KEY}}
